CREATE TABLE IF NOT EXISTS customization_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) NOT NULL UNIQUE,
  customer_id INT NOT NULL,
  garment_type VARCHAR(100) NOT NULL,
  fabric_type VARCHAR(100) NULL,
  measurements TEXT NULL,
  design_description TEXT NULL,
  estimated_completion_date DATE NULL,
  price DECIMAL(10,2) NULL,
  color VARCHAR(100) NULL,
  style VARCHAR(100) NULL,
  quantity INT NOT NULL DEFAULT 1,
  embellishments TEXT NULL,
  special_instructions TEXT NULL,
  order_date DATE NULL,
  due_date DATE NULL,
  additional_charges DECIMAL(10,2) NOT NULL DEFAULT 0,
  discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(10,2) NULL,
  amount_paid DECIMAL(10,2) NOT NULL DEFAULT 0,
  balance DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
  delivery_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  status VARCHAR(50) NOT NULL DEFAULT 'received',
  notes TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT
);
